package databasemanager;

import console.Console;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nimda
 */
public class Tickermngmnt extends javax.swing.JFrame {

    private final Console myconsole;
    private final String myhome;
    private final Statement mystm;

    /**
     * Creates new form NewTicker
     */
    Tickermngmnt(Console console, String home, Statement stm) {
        initComponents();
        myconsole = console;
        myhome = home;
        mystm = stm;
        myconsole.setFocusable(true);
        myconsole.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        symbol = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        descr = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        remove = new javax.swing.JButton();

        setTitle("Manage tickers");
        setLocation(new java.awt.Point(525, 125));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ticker (official)");

        symbol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        symbol.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Description");

        descr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        remove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(remove))
                    .addComponent(symbol)
                    .addComponent(descr, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(symbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(descr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(remove))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        try {
            String cmd = String.format("insert into tickers(symb, name) values (\"%s\", \"%s\")",
                    symbol.getText(),
                    descr.getText()
            );
            mystm.executeUpdate(cmd);
            myconsole.textArea.append("ticker successfully added to the database.\n");
        } catch (SQLException ex) {
            Logger.getLogger(Tickermngmnt.class.getName()).log(Level.SEVERE, null, ex);
            myconsole.textArea.append(ex.toString() + "\n");
        }
    }//GEN-LAST:event_addActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        try {
            myconsole.setVisible(true);
            myconsole.setFocusableWindowState(true);
            String cmd = String.format("select _id from tickers where symb = \"%s\"",
                    symbol.getText()
            );
            ResultSet rs = mystm.executeQuery(cmd);
            rs.next();
            int tick_id = rs.getInt(1);
            cmd = String.format("delete from stocks where tick =%d", tick_id);
            mystm.executeUpdate(cmd);
            cmd = String.format("delete from tickers where symb = \"%s\"",
                    symbol.getText()
            );
            myconsole.textArea.append("ticker successfully removed from the database.\n");
            mystm.executeUpdate(cmd);
        } catch (SQLException ex) {
            Logger.getLogger(Tickermngmnt.class.getName()).log(Level.SEVERE, null, ex);
            myconsole.textArea.append(ex.toString() + "\n");
        }
    }//GEN-LAST:event_removeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField descr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton remove;
    private javax.swing.JTextField symbol;
    // End of variables declaration//GEN-END:variables
}
